### ISSUE TITLE
gin框架用了一个模型校验器，考虑一下呗

### ISSUE THREAD

**Issue by icetech233** [yoyofx/yoyogo#144]
github.com/go-playground/validator/v10

**Comment by yoyofx** [comment]
只是集成吗，可以的 ，这块确实考虑过的，安排！

**Comment by yoyofx** [comment]
> github.com/go-playground/validator/v10

可以加群咱们一起讨论，readme.md上有

**Comment by yoyofx** [comment]
决定重构 binding 参考 https://github.com/gin-gonic/gin/tree/master/binding

**Comment by yoyofx** [comment]
Upgrade in v1.6.9

**Comment by icetech233** [comment]
> 决定重构 binding 参考 https://github.com/gin-gonic/gin/tree/master/binding @Artanis-c

对的，gin 就是这边 调用实现的，qq群里联系不上你

**Comment by yoyofx** [comment]
> > 决定重构 binding 参考 https://github.com/gin-gonic/gin/tree/master/binding @Artanis-c
> 
> 对的，gin 就是这边 调用实现的，qq群里联系不上你

你加我微信吧  ，  maxzhang1985   ， 我拉你到 微信群， QQ一般不上了

**Comment by yoyofx** [comment]
Enter the testing period

**Comment by yoyofx** [comment]
fixed
