### ISSUE TITLE
max_request_size 设置后没有起作用

### ISSUE THREAD

**Issue by top3372** [yoyofx/yoyogo#187]
设置了 max_request_size 后  
上传 小一点的文件 没问题 ,
大一点的文件 就报  body size exceeds the given limit

**Comment by yoyofx** [comment]
max_request_size 在 fasthttp中没有生效，修复代码已提交，将在11-12号测试完成后，合并发布新版本中修复。

Thank you for your issues.

**Comment by yoyofx** [comment]
fixed
