### ISSUE TITLE
错误日志无法输出堆栈

### ISSUE THREAD

**Issue by Artanis-c** [yoyofx/yoyogo#191]
使用框架时程序出现500错误，但是控制台中只输出了错误的信息，并没有输出错误的堆栈，导致查找问题代码十分困难，建议输出全量堆栈信息。
2021/11/09 16:31:26.43 - [YOYOGO] - [INFO] [yoyogo] 2021/11/09 - 16:31:26.38 | 200 |      53 ms|  localhost:8080 |   GET  /v1/tenant/tenantlist?pageSize=20&tCode=44444&pageIdnex=1&pageIndex=1 
2021/11/09 16:51:45.85 - [YOYOGO] - [INFO] [yoyogo] Method: GET Url: /v1/cluster/list?current=1&pageSize=20  Content-Type:  , Accept: */*
2021/11/09 16:51:45.85 - [YOYOGO] - [ERROR] { "Result": -1 , "Data": "error", "Message": "interface conversion: interface {} is nil, not map[string]interface {}" }%!(EXTRA string=)
2021/11/09 16:51:45.85 - [YOYOGO] - [INFO] [yoyogo] 2021/11/09 - 16:51:45.85 | 500 |       8 ms|  localhost:8080 |   GET  /v1/cluster/list?current=1&pageSize=20

**Comment by yoyofx** [comment]
解决
