### ISSUE TITLE
配置文件节点支持环境变量

### ISSUE THREAD

**Issue by yoyofx** [yoyofx/yoyogo#201]
## 配置文件环境变量 表达式如下：
```${ENV:defaultValue}```

## 例如yaml:
```yaml
yoyogo:
   user:
      name: ${USERNAME:helloworld}
```

**Comment by Artanis-c** [comment]
已添加环境变量支持
env: ${MAVEN_HOME}
profile:
  homebrew: ${HOMEBREW_BOTTLE_DOMAIN}
  default: ${DEFAULT:yoyogoDefault}
	str := config.Get("env")
	str2 := config.Get("profile.homebrew")
	str3 := config.Get("profile.default")
	fmt.Println(str)
	fmt.Println(str2)
	fmt.Println(str3)
2022/04/22 15:32:16.77 - [YOYOGO] - [DEBUG] config_dev.yml
开始处理
环境变量值/Users/cui/Documents/apache-maven-3.8.1
开始处理
环境变量值https://mirrors.aliyun.com/homebrew/homebrew-bottles
开始处理
环境变量值<nil>
默认值yoyogoDefault
2
/Users/cui/Documents/apache-maven-3.8.1
https://mirrors.aliyun.com/homebrew/homebrew-bottles
yoyogoDefault
--- PASS: TestEnv (0.00s)
PASS

**Comment by Artanis-c** [comment]
源码实现
func (c *Configuration) BindEnvironment(key string, originalKey string) {
	//fmt.Println("两个参数")
	//fmt.Println(key + "---" + originalKey)
	key = key[2 : len(key)-1]
	envKeyDefaultValue := strings.Split(key, ":")
	if len(envKeyDefaultValue) > 2 {
		panic("can't read environment for illegal key:" + key)
	}
	envKey := envKeyDefaultValue[0]
	//fmt.Println("环境变量key" + envKey)
	viper.BindEnv(envKey)
	envValue := viper.Get(envKey)
	if envValue == nil {
		if len(envKeyDefaultValue) > 1 {
			c.config.Set(originalKey, envKeyDefaultValue[1])
			return
		}
	}
	c.config.Set(originalKey, envValue)
}

func (c *Configuration) AssertEnvironment(key string) bool {
	if len(key) < 2 {
		return false
	}
	prefix := key[0:2]
	last := key[len(key)-1:]
	if !(prefix == "${" && last == "}") {
		return false
	}
	return true
}

**Comment by yoyofx** [comment]
配置文件单节点获取已支持，感谢 @Artanis-c 的贡献，
同时还需要获取配置对象的能力，在abstractions/default_viper_configuration.go 下的 GetConfigObject函数

**Comment by yoyofx** [comment]
功能已完成
### Such as YAML:
```yaml
env: ${CUSTOM_ENV}
profile:
  dns: ${REMOTE_HOST}
  ip: ${REMOTE_IP:10.0.1.12}
  namespace: ${MYNAMESPACE:space.localhost}
```

### Go Example
```go
type Profile struct {
	DNS string `config:"dns"`
	IP  string `config:"ip"`
	NS  string `config:"namespace"`
}

config := abstractions.NewConfigurationBuilder().
       AddEnvironment().
       AddYamlFile("config").Build()

config.GetConfigObject("profile", &profile)
assert.Equal(t, profile.NS, "space.yoyogo.run")
assert.Equal(t, profile.DNS, "my host")
assert.Equal(t, profile.IP, "10.0.1.12")
```
or

```go
env := config.Get("env")
dns := config.Get("profile.dns")
ip := config.Get("profile.ip")

assert.Equal(t, env, "my env variable")
assert.Equal(t, dns, "my host")
assert.Equal(t, ip, "10.0.1.12")
```
