### ISSUE TITLE
文档中的简单实例无法启动

### ISSUE THREAD

**Issue by Artanis-c** [yoyofx/yoyogo#98]
使用文档中的简单实例代码放到本地执行后，无法正常启动监听端口，没有出现文档中的效果图

error:panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x20 pc=0x6e2685]

**Comment by yoyofx** [comment]
v1.5.5 中 CreateDefaultBuilder 由于找不到配置，而报错！

**Comment by yoyofx** [comment]
将在 v1.5.7 中 修复
